export const api = [
  {
    id: "1",
    name: "eg - list name 1",
    date: "Aug",
    year: "2020",
    week: "4",
    price: "$2.00",
    tax: "50.00%",
  },
  {
    id: "2",
    name: "eg - list name 2",
    date: "Aug",
    year: "2020",
    week: "4",
    price: "$3.00",
    tax: "19.00%",
  },
  {
    id: "3",
    name: "eg - list name 3",
    date: "Aug",
    year: "2020",
    week: "3",
    price: "$3.12",
    tax: "1.00%",
  },
  {
    id: "4",
    name: "eg - list name 4",
    date: "Aug",
    year: "2019",
    week: "4",
    price: "$1.12",
    tax: "1.00%",
  },
  {
    id: "5",
    name: "eg - list name 5",
    date: "Aug",
    year: "2019",
    week: "3",
    price: "$10.12",
    tax: "1.00%",
  },
  {
    id: "6",
    name: "eg - list name 6",
    date: "Sep",
    year: "2018",
    week: "4",
    price: "$10.00",
    tax: "1.00%",
  },
  {
    id: "7",
    name: "eg - list name 7",
    date: "Sep",
    year: "2015",
    week: "4",
    price: "$5.00",
    tax: "1.00%",
  },
  {
    id: "8",
    name: "eg - list name 8",
    date: "Oct",
    year: "2015",
    week: "3",
    price: "$12.00",
    tax: "1.00%",
  },
  {
    id: "9",
    name: "eg - list name 9",
    date: "Dec",
    year: "2018",
    week: "2",
    price: "$100",
    tax: "1.00%",
  },
  {
    id: "10",
    name: "eg - list name 10",
    date: "Dec",
    year: "2018",
    week: "3",
    price: "$200",
    tax: "9.60%",
  },
];
